#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armRight,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           clawOpen,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void armUp(){
	motor[armLeft] = -120;
	motor[armRight] = -120;
}

void armDown(){
	motor[armLeft] = -50;
	motor[armRight] = -50;
}

void stopArm(){
	motor[armLeft] = 0;
	motor[armRight] = 0;
}

void clawO(){
	motor[clawOpen] = 50;
}

void clawC(){
	motor[clawOpen] = -50;
}

void clawS(){
	motor[clawOpen] = 0;
}

void moveForward(){

	motor[frontLeft] = 87;
	motor[frontRight] = 127;
	motor[backLeft] = 87;
	motor[backRight] = 87;

}

void moveBackward(){

	motor[frontLeft] = -87;
	motor[frontRight] = -127;
	motor[backLeft] = -87;
	motor[backRight] = -87;

}

void stopMoving() {

motor[frontLeft] = 0;
	motor[frontRight] = 0;
	motor[backLeft] = 0;
	motor[backRight] = 0;

}

void rotateRight() {

motor[frontLeft] = 87;
motor[backLeft] = 127;
motor[frontRight] = -87;
motor[backRight] = -87;

}

void rotateLeft() {

	motor[frontLeft] = -87;
	motor[backLeft] = -127;
	motor[frontRight] = 87;
	motor[backRight] = 87;
}

task main()
{
moveForward();
wait1Msec(3000);
stopMoving();
rotateRight();
wait1Msec(1900);
stopMoving();
moveForward();
wait1Msec(1000);
stopMoving();
rotateRight();
wait1Msec(600);
stopMoving();
moveBackward();
wait1Msec(1000);
stopMoving();
rotateRight();
wait1Msec(1900);
stopMoving();
moveBackward();
wait1Msec(4500);
stopMoving();
}
