#pragma config(Sensor, in1,    potentio,       sensorPotentiometer)
#pragma config(Motor,  port8,           clawT,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           clawM,         tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (1==1){
		if(vexRT[Btn8R] == 1){
			//potentiometer?
			motor[clawM] = 50;
			motor[clawM] = -50;
		}
		while(vexRT[Btn6D] == 1){
			motor[clawT] = 50;
		}
		while(vexRT[Btn6U] == 1){
			motor[clawT] = -50;
		}
		motor[clawT] = 0;
	}

}
