#pragma config(Motor,  port6,           leftarm,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           rightarm,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void armUp(){
		motor[leftarm] = 120;
		motor[rightarm] = 120;
}

void armDown(){
		motor[leftarm] = -120;
		motor[rightarm] = -120;
}

void stopArm(){
		motor[leftarm] = 0;
		motor[rightarm] = 0;
}

task main()
{
	while(1==1){
		if(vexRT[Btn5U]== 1){
			armUp();
		}
		if(vexRT[Btn5D]== 1){
			armDown();
		}
		stopArm();
	}
}
