#pragma config(Motor,	 port2,						rightB,				 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port3,						rightF,				 tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,	 port4,						leftB,				 tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,	 port5,						leftF,				 tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

task main()
{
	int channelvar_two = 0;
	int channelvar_three = 0;
	int channelvar_four = 0;
	int threshold = 15;
	while(1==1){


		//creating a deadzone for channel 2
		if (abs(vexRT[Ch2]) > threshold){
			channelvar_two = vexRT[Ch2];
			} else{
			channelvar_two= 0;
		}

		//creating a deadzone for channel 3
		if (abs(vexRT[Ch3]) > threshold){
			channelvar_three = vexRT[Ch3];
			} else{
			channelvar_three = 0;
		}

		//creating a deadzone for channel 4
		if (abs(vexRT[Ch4]) > threshold){
			channelvar_four = vexRT[Ch4];
			} else{
			channelvar_four = 0;
		}

		//moving the robot

		motor[rightF] = channelvar_three - channelvar_four - channelvar_two;
		motor[rightB] = channelvar_three - channelvar_four + channelvar_two;
		motor[leftF]  = channelvar_three + channelvar_four + channelvar_two;
		motor[leftB]  = channelvar_three + channelvar_four - channelvar_two;

	}
}
