#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           frontLeft,     tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           backRight,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           armRight,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port7,           armLeft,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port8,           clawOpen,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void armUp(){
	motor[armLeft] = -120;
	motor[armRight] = -120;
}

void armDown(){
	motor[armLeft] = 50;
	motor[armRight] = 50;
}

void stopArm(){
	motor[armLeft] = -10;
	motor[armRight] = -10;
}

void clawO(){
	motor[clawOpen] = 50;
}

void clawC(){
	motor[clawOpen] = -50;
}

void clawS(){
	motor[clawOpen] = 0;
}

task base()
{
	int channelvar_one = 0;
	int channelvar_three = 0;
	int channelvar_four = 0;
	int threshold = 15;

	while(true){
		//creating a deadzone for channel 2
		if (abs(vexRT[Ch1]) > threshold){
			channelvar_one = vexRT[Ch1];
		}
		else{
			channelvar_one= 0;
		}

		//creating a deadzone for channel 3
		if (abs(vexRT[Ch3]) > threshold){
			channelvar_three = vexRT[Ch3];
		}
		else{
			channelvar_three = 0;
		}

		//creating a deadzone for channel 4
		if (abs(vexRT[Ch4]) > threshold){
			channelvar_four = vexRT[Ch4];
		}
		else{
			channelvar_four = 0;
		}

		//moving the robot

		motor[frontRight] = channelvar_three - channelvar_four + channelvar_one;
		motor[backRight] = channelvar_three - channelvar_four - channelvar_one;
		motor[frontLeft]  = channelvar_three + channelvar_four - channelvar_one;
		motor[backLeft]  = channelvar_three + channelvar_four + channelvar_one;
	}
}

task arm()
{
	while (true){
		while(vexRT[Btn5U]== 1){
			armUp();
		}
		while(vexRT[Btn5D]== 1){
			armDown();
		}
		stopArm();
	}
}

task claw()
{
	while (true){
		while(vexRT[Btn6U] == 1){
			clawO();
		}
		while(vexRT[Btn6D]== 1){
			clawC();
		}
		clawS();
	}
}

task main()
{
	startTask(base);
	startTask(arm);
	startTask(claw);
	while (true){
		wait1Msec(1);
	}
}
