#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  baseRightIME,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  baseLeftIME,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           baseRight,     tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           baseLeft,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port4,           mobileLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           mobileRight,   tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void mobileUp(){
	motor[mobileLeft] = -127;
	motor[mobileRight] = -127;
	wait1Msec(400);
}

void mobileDown(){
	motor[mobileLeft] = 127;
	motor[mobileRight] = 127;
	wait1Msec(400);
}

void mobileStop(){
	motor[mobileLeft] = 0;
	motor[mobileRight] = 0;
}

void mobileStay(){
	motor[mobileLeft] = -63;
	motor[mobileRight] = -63;
}

task base()
{
	int channelvar_three = 0;
	int channelvar_four = 0;
	int channelvar_one = 0;
	int channelvar_two = 0;
	int threshold = 15;

	while(true){

		//creating a deadzone for channel 3
		if (abs(vexRT[Ch3]) > threshold){
			channelvar_three = vexRT[Ch3];
		}
		else{
			channelvar_three = 0;
		}

		//creating a deadzone for channel 4
		if (abs(vexRT[Ch4]) > threshold){
			channelvar_four = vexRT[Ch4];
		}
		else{
			channelvar_four = 0;
		}

		//creating a deadzone for channel 1
		if (abs(vexRT[Ch1]) > threshold){
			channelvar_one = vexRT[Ch1];
		}
		else{
			channelvar_one = 0;
		}

		//creating a deadzone for channel 2
		if (abs(vexRT[Ch2]) > threshold){
			channelvar_two = vexRT[Ch2];
		}
		else{
			channelvar_two = 0;
		}

		//moving the robot

		motor[baseRight] = (-channelvar_two);
		motor[baseLeft]  = (-channelvar_three);
	}
}

task mobileGoal()
{
	bool mobile_up = false;
	while (true){
		if(vexRT[Btn7UXmtr2]== 1){
			mobileUp();
			mobile_up = true;
		}
		if(vexRT[Btn7DXmtr2]== 1){
			mobileDown();
			mobile_up = false;
		}
		if (mobile_up == true){
			mobileStay();
			} else{
			mobileStop();
		}
	}
}

task main()
{
	startTask(base);
	startTask(mobileGoal);
	while (true){
		wait1Msec(1);
	}
}
